### PR TITLE
Convert periodic_field_update for GPU execution

### PR DESCRIPTION
**Pull request by alanw0**
Passes all tests on CPU, checked build and execution using
periodic3dEdge on GPU. (Test still doesn't pass, but runs to
completion.)

### CODE REVIEW

**Comment by alanw0** [comment]
Note that this pull-request shouldn't be merged until nalu-wind has updated Trilinos to be newer than yesterday morning or so. (I can provide sha1 if needed.)

**Comment by sayerhs** [comment]
@alanw0 I think it would be a good idea to allow for both on-host and on-device exchanges for these methods, and we could control at the call site how we want the exchanges happening. There are situations (where we will still need some things to happen on host, e.g., during initialization, transfers, overset ghosting changes) and at that point it might be better to pull the fields to host do the non-ngp algorithms on host, perform parallel communication on host fields, and then push it back to device as necessary. Can we retain the old methods and rename the new ones `ngp_periodic_field_update` and so on, so that we can explicitly transition these calls one by one.

**Comment by alanw0** [comment]
@sayerhs yes that's easy and sounds reasonable. I've got a chopped up day today with sprint meetings but I'll put in a revised commit soon.

**Comment by alanw0** [comment]
Ok I think this is merge-able now. Realm methods are calling the non-ngp versions of the PeriodicManager methods, can be switched to ngp versions when ready. I'll do the apply_max_field conversion next.

**Pull request merged**
