### PR TITLE
Convert field updates to NGP versions

### PR DESCRIPTION
**Pull request by sayerhs**
Synchronize fields to device after a linear system solve. Addresses the
`field_axpby` part in #301

### CODE REVIEW

**Comment by sayerhs** [comment]
@alanw0 This pull request just creates a wrapper to ensure that the updates to the field by `field_axpby` is pushed down to the device for use after a linear system solve. For the september GPU demonstration target, my assumption is that `copy_tpetra_to_stk` 

https://github.com/Exawind/nalu-wind/blob/0e87d37630507f4ea8ce5e1f0078b6af5d4323c3/src/TpetraLinearSystem.C#L1833

will use Tpetra's UVM to copy the solution vector on host. If we go this route, then all the MPI send/recv activity that happens in the subsequent calls listed in #301 will be taken care of. Since periodic involves some ghosting (although it doesn't change), it allows us to get to a working prototype while STK team is implementing the on-device send/recv for `ngpField`. When that happens it is just a matter of replacing the implementation of `solution_update` instead of modifying code in all the `solve_and_update` implementations.

**Comment by sayerhs** [comment]
@alanw0 No, I haven't touched the other items in #301 as I figured you were already dealing with those. For `copy_tpetra_to_stk` we are just making sure that the device solution can be updated on `BulkData` fields correct? Or are you planning to move the logic in there to device? I suspect since we have to do MPI communications, it is probably better to leave it as it is and just ensure that the solution is transferred after a solve. Thoughts?

**Comment by alanw0** [comment]
@sayerhs currently the (simple) parallel_sum for ngp::Fields brings the data from device to host, does MPI communication, then brings the data back to device. In other words the idea is that the data is on device before and after parallel_sum. The (smart) implementation is under way, which keeps the data on device and does MPI communication with device pointers. What other MPI communication do we need to do? communicate_field_data for periodic? We'll work on the ngp version of that next. Once that is done, we might be able to keep data on device through multiple time-steps right? If so, then maybe we should make copy_tpetra_to_stk copy the data straight from the device-resident tpetra solution vector into the device-resident ngp::Field. As you mentioned, tpetra's UVM model will help us out when we reference data in the wrong place, but I think we're getting close to keeping data on device and just bringing it back to host for I/O.

**Comment by sayerhs** [comment]
@alanw0 Yes, if we can get 

- `stk::mesh::copy_owned_to_shared`
- `stk::mesh::communicate_field_data`

working to synchronize `ngp::Field` then we can update the field from linear solve directly on device, and then avoid having to move things to CPU. We might still have some algorithms on Nalu side that are still running on CPU and, therefore, we might still explicitly move things in the short term.

**Comment by jrood-nrel** [comment]
Do we need a matching update to Trilinos/STK for this? Has it already happened?

**Comment by alanw0** [comment]
@jrood-nrel yes we'll need a separate stk-to-trilinos update for copy_owned_to_shared and communicate_field_data. We'll try to get those in soon.

**Comment by sayerhs** [comment]
Will implement using NgpFieldBLAS functions introduced in #342

**Pull request closed without merging**
