### PR TITLE
Use hypre for convTaylorVortex case

### PR DESCRIPTION
**Pull request by marchdf**
This should fix one of the dashboard issues.

### CODE REVIEW

**Comment by marchdf** [comment]
Linked to #1289

**Review by jrood-nrel — COMMENTED** [review]
I think you need these https://github.com/Exawind/exawind-driver/blob/1f6c2aa931b9c01412da9c686d4224f0ce2a2614/test/test_files/flat-surface/flat-surface-nalu.yaml#L15-L16

**Comment by marchdf** [comment]
Probably. I grabbed the section from ablNeutralNGPHypre.yaml. That file doesn't have these. Should I add them there too?

**Comment by marchdf** [comment]
nvm the abl thing I refered to above has: `hypre_cfg_file: ../../hypre_settings/hypre_blade_resolved.yaml`, which contains those settings.

**Review by jrood-nrel — APPROVED** [review]

**Pull request merged**
