### PR TITLE
Changes to CMake

### PR DESCRIPTION
**Pull request by jrood-nrel**

### CODE REVIEW

**Comment by lucbv** [comment]
@jrood-nrel fyi, this works fine on Summit, I'll do a local build on Sandia machines and let you know how it goes there.
Also do you want me to make a request for a more recent version of CMake to be installed as a module at Sandia? If so just let me know what version makes sense and I'll put the request in.

**Comment by jrood-nrel** [comment]
Thanks @lucbv . We can probably let CMake on Sandia machines get updated naturally. I don't have any future changes in mind beyond this PR that would require any new versions. I would be curious to know if there is anyone left on the project who requires yaml-cpp 0.5.3 because we can remove several lines of code if we are able to deprecate that version.

**Comment by lucbv** [comment]
@jrood-nrel locally our modules provide `yaml-cpp 0.5.3` but I have been using a local build of `yaml-cpp 0.6.2` and I think that @jhux2 does too. However it would be best to have the `0.6.2` installed as a module if we make it a requirement. I will look into it.

My local build did not go through, it fails during configuration here is the output I am getting from CMake:

```
[lberge@trappist nalu_build]$ ../../scripts/configure_nalu.sh
Nalu source dir:  "/ascldap/users/lberge/Research/codes/ExaWind/sources/nalu-wind"
Nalu build dir:   "/ascldap/users/lberge/Research/codes/ExaWind/builds/nalu_build"
trilinos install dir: "/ascldap/users/lberge/Research/codes/ExaWind/installs/trilinos"
-- The CXX compiler identification is GNU 7.2.0
-- The Fortran compiler identification is GNU 7.2.0
-- Check for working CXX compiler: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/bin/g++
-- Check for working CXX compiler: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working Fortran compiler: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/bin/gfortran
-- Check for working Fortran compiler: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/bin/gfortran supports Fortran 90
-- Checking whether /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/bin/gfortran supports Fortran 90 -- yes
-- Found MPI_CXX: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/lib/libmpi_cxx.so (found version "3.0") 
-- Found MPI_Fortran: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/lib/libmpi_usempif08.so (found version "3.0") 
-- Found MPI: TRUE (found version "3.0")  
-- Found Trilinos = /ascldap/users/lberge/Research/codes/ExaWind/installs/trilinos/lib/cmake/Trilinos
-- Found YAML-CPP = /home/lberge/Research/codes/yaml/yaml-cpp_0_6_2
-- CMAKE_SYSTEM_NAME = Linux
-- CMAKE_CXX_COMPILER_ID = GNU
-- CMAKE_BUILD_TYPE = RELEASE
CMake Error at CMakeLists.txt:233 (set_target_properties):
  set_target_properties Can not find target to add properties to: PUBLIC


-- Using test tolerance of 0.000000000000001
-- Configuring incomplete, errors occurred!
See also "/ascldap/users/lberge/Research/codes/ExaWind/builds/nalu_build/CMakeFiles/CMakeOutput.log".
```

and here is the content of my configure script;

```
rm -f CMakeCache.txt
rm -rf CMakeFiles

cmake \
    -D CMAKE_CXX_FLAGS:STRING="-Wno-deprecated-declarations ${FLAGS}" \
    -D CMAKE_C_FLAGS:STRING="-Wno-deprecated-declarations ${FLAGS}" \
    -D CMAKE_Fortran_FLAGS:STRING="${FLAGS}" \
    -D Trilinos_DIR:PATH="${trilinos_install_dir}" \
    -D YAML_DIR:PATH="${YAML_CPP_0_6_2}" \
    -D YAML_CPP_LIBRARIES:PATH="${YAML_CPP_0_6_2}/lib" \
    -D ENABLE_HYPRE:BOOL=OFF \
    -D ENABLE_TIOGA:BOOL=OFF \
    -D CMAKE_BUILD_TYPE:STRING=RELEASE \
    -D ENABLE_DOCUMENTATION:BOOL=OFF \
    -D ENABLE_TESTS:BOOL=ON \
    -D CMAKE_SKIP_BUILD_RPATH:BOOL=FALSE \
    -D CMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=FALSE \
    -D CMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=TRUE \
    -D CMAKE_BUILD_RPATH:STRING="${YAML_CPP_0_6_2}/lib;${trilinos_install_dir}/lib;$(pwd)" \
    $nalu_source_dir |& tee "${nalu_build_dir}/configure.log"
```

**Comment by jrood-nrel** [comment]
@lucbv Thanks for trying this. I made a commit that should hopefully fix that issue.

**Comment by lucbv** [comment]
@jrood-nrel, I pulled the new commit and was able to configure correctly, I am know waiting for the build to finish, will update on that soon!

**Comment by lucbv** [comment]
@jrood-nrel the build has completed successfully and running `ctest -R` is giving correct results so I am OK with your changes.

**Pull request merged**
