### PR TITLE
Fix nrel5MWactuatorLine test and ActuatorBulkFastTests unit test

### LINKED ISSUE #1283: nrel5MWactuator* reg tests fail with segfault
Information I have so far:

backtrace:
```
* thread #1, name = 'naluX', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x0)
  * frame #0: 0x00007fffef78c6a4 libopenfastcpplib.so`fast::OpenFAST::allocateMemory_preInit(this=0x0000000000709b50) at OpenFAST.cpp:2072:49
    frame #1: 0x00007fffef77f71c libopenfastcpplib.so`fast::OpenFAST::init(this=0x0000000000709b50) at OpenFAST.cpp:635:27
    frame #2: 0x00007ffff6bf93d0 libnalu.so`void std::__invoke_impl<void, void (fast::OpenFAST::*&)(), fast::OpenFAST*&>((null)=__invoke_memfun_deref @ 0x00007fffffff1680, __f=0x0000000000712ea0, __t=0x0000000000712eb0) at invoke.h:74:46
    frame #3: 0x00007ffff6bf9231 libnalu.so`std::__invoke_result<void (fast::OpenFAST::*&)(), fast::OpenFAST*&>::type std::__invoke<void (fast::OpenFAST::*&)(), fast::OpenFAST*&>(__fn=0x0000000000712ea0, (null)=0x0000000000712eb0) at invoke.h:96:40
    frame #4: 0x00007ffff6bf8fe8 libnalu.so`void std::_Bind<void (fast::OpenFAST::* (fast::OpenFAST*))()>::__call<void, 0ul>(this=0x0000000000712ea0, __args=0x00007fffffff16ff, (null)=_Index_tuple<0> @ 0x00007fffffff16e0) at functional:495:24
    frame #5: 0x00007ffff6bf8d8a libnalu.so`void std::_Bind<void (fast::OpenFAST::* (fast::OpenFAST*))()>::operator()<void>(this=0x0000000000712ea0) at functional:580:32
    frame #6: 0x00007ffff6bf7faa libnalu.so`void std::__invoke_impl<void, std::_Bind<void (fast::OpenFAST::* (fast::OpenFAST*))()>&>((null)=__invoke_other @ 0x00007fffffff1730, __f=0x0000000000712ea0) at invoke.h:61:36
    frame #7: 0x00007ffff6bf7684 libnalu.so`std::enable_if<is_invocable_r_v<void, std::_Bind<void (fast::OpenFAST::* (fast::OpenFAST*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (fast::OpenFAST::* (fast::OpenFAST*))()>&>(__fn=0x0000000000712ea0) at invoke.h:111:28
    frame #8: 0x00007ffff6bf68f3 libnalu.so`std::_Function_handler<void (), std::_Bind<void (fast::OpenFAST::* (fast::OpenFAST*))()>>::_M_invoke(__functor=0x00007fffffff1ce0) at std_function.h:290:30
    frame #9: 0x00007ffff6bf43d2 libnalu.so`std::function<void ()>::operator()(this=0x00007fffffff1ce0) const at std_function.h:591:9
    frame #10: 0x00007ffff6bf3d17 libnalu.so`sierra::nalu::squash_fast_output(func=function<void()> @ 0x00007fffffff1ce0) at ActuatorBulkFAST.h:81:7
    frame #11: 0x00007ffff6bed826 libnalu.so`sierra::nalu::ActuatorBulkFAST::init_openfast(this=0x0000000000709580, actMeta=0x00000000006cad90, naluTimeStep=0.0625) at ActuatorBulkFAST.C:109:23
    frame #12: 0x00007ffff6bed210 libnalu.so`sierra::nalu::ActuatorBulkFAST::ActuatorBulkFAST(this=0x0000000000709580, actMeta=0x00000000006cad90, naluTimeStep=0.0625) at ActuatorBulkFAST.C:58:16
    frame #13: 0x00007ffff6b6733a libnalu.so`sierra::nalu::ActuatorModel::setup(this=0x0000000000602290, timeStep=0.0625, stkBulk=0x00000000006cdf60) at ActuatorModel.C:87:60
    frame #14: 0x00007ffff6b62734 libnalu.so`sierra::nalu::AeroContainer::setup(this=0x0000000000602290, timeStep=0.0625, bulk=ptr = 0x6cdf60) at AeroContainer.C:89:25
    frame #15: 0x00007ffff699862d libnalu.so`sierra::nalu::Realm::initialize_prolog(this=0x00000000006c8d00) at Realm.C:434:23
    frame #16: 0x00007ffff69d3b66 libnalu.so`sierra::nalu::Realms::initialize_prolog(this=0x00000000006a17d0) at Realms.C:75:29
    frame #17: 0x00007ffff6a034d2 libnalu.so`sierra::nalu::Simulation::initialize(this=0x00007fffffff2570) at Simulation.C:184:29
    frame #18: 0x0000000000428dfa naluX`main(argc=5, argv=0x00007fffffff31a8) at nalu.C:197:19
    frame #19: 0x00007fffe739a7e5 libc.so.6`__libc_start_main + 229
    frame #20: 0x0000000000427a7e naluX`_start + 46
```
This is the offender:
```
(lldb) print globTurbineData
(std::vector<fast::turbineDataType>) size=1 {
  [0] = {
    TurbID = 1
    FASTInputFileName = "nrel5mw.fst"
    FASTRestartFileName = "blah"
    outFileRoot = ""
    dt = 0
    TurbineBasePos = size=3 {
      [0] = 0
      [1] = 0
      [2] = 0
    }
    TurbineHubPos = size=0 {}
    sType = EXTINFLOW
    numBlades = 0
    numVelPtsBlade = 0
    numVelPtsTwr = 0
    numVelPts = 0
    numForcePtsBlade = 50
    numForcePtsTwr = 20
    numForcePts = 0
    nodeClusterType = 0
    inflowType = 0
    nacelle_cd = 1
    nacelle_area = 8
    air_density = 1.22500002
    nBRfsiPtsBlade = size=0 {}
    nTotBRfsiPtsBlade = 0
    nBRfsiPtsTwr = 0
    azBlendMean = 0
    azBlendDelta = 0
    velMean = 0
    windDir = 0
    zRef = 0
    shearExp = 0
  }
}
```

Notice: `TurbineHubPos = size=0 {}` . Which means this call will fail: https://github.com/OpenFAST/openfast/blob/dev/glue-codes/openfast-cpp/src/OpenFAST.cpp#L2072

So the turbine hub position isn't getting passed in right. Not sure why yet... I tried the obvious thing and added `turbine_hub_pos` to the yaml input file. No luck.

### PR DESCRIPTION
**Pull request by marchdf**
This is the fix to the segfault in `nrel5MWactuatorLine`. https://github.com/OpenFAST/openfast/blob/dev/glue-codes/openfast-cpp/src/OpenFAST.cpp#L2072 needs valid values in `TurbineHubPos`. Curious to get thoughts from people who know this stuff better: @psakievich and @gantech.

Not quite the end of the story because the input files have drifted from the dev openfast so I still need to fix 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  FAST_InitializeAll:FAST_Init:FAST_ReadPrimaryFile:Invalid numerical input for file "nrel5mw.fst" occurred while trying to read MHK
```

But that's much easier to deal with ;)

### CODE REVIEW

**Comment by marchdf** [comment]
actually I have no idea why it is complaining about MHK...

**Comment by marchdf** [comment]
Ah it's missing sea state information.

**Comment by marchdf** [comment]
Ok now dealing with:
```
 OpenFAST input file heading:
     FAST Certification Test #01: NREL 5.0 MW Baseline Wind Turbine (Onshore)

terminate called after throwing an instance of 'std::runtime_error'
  what():  FAST_InitializeAll:FAST_Init:ValidateInputData:DT_out must be at least DT (6.25000E-03 s).
```

**Comment by jrood-nrel** [comment]
I updated openfast input files here which might help https://github.com/Exawind/exawind-cases/pull/25

**Comment by marchdf** [comment]
yeah I've been digging around the openfast site. It's tricky because everything is on the dev branch because that's what we use with +fsi. 

This is a bit of a maddening exercise though. My two current issues:
- I need to provide a `dtDriver` to the fast data. No idea what that should be so I hacked in a fixed value. But maybe it needs to be the nalu-wind time step? Not sure how to get that value where it is needed in the actuator parser.
- Even if that is fixed, there is still the fact that it is failing at:
```
naluX: putget.m4:745: putNCvx_double_double: Assertion `value != NULL' failed.

(lldb) frame s 8
frame #8: 0x00007fffef77dac6 libopenfastcpplib.so`fast::OpenFAST::prepareOutputFile(this=0x0000000000709630, iTurbLoc=0) at OpenFAST.cpp:615:33
   612              }
   613          }
   614
-> 615          ierr = nc_put_var_double(ncid, ncOutVarIDs_["nac_ref_pos"],
   616                                   &brFSIData[iTurbLoc][3].nac_ref_pos[0]);
   617          ierr = nc_put_var_double(ncid, ncOutVarIDs_["nac_ref_orient"],
   618                                   &brFSIData[iTurbLoc][3].nac_ref_pos[3]);
(lldb)
```

Also should be noted that if this is all fixed, we still have a problem that these input files will only work with dev openfast, which means this test will only work with +fsi. 

I will take anyone's suggestions on how to proceed. Ideally someone who has looked at openfast/nalu-wind coupling. 

Tagging: @psakievich, @gantech, @lawrenceccheung, @neilmatula , @ndevelder

**Comment by marchdf** [comment]
I got to a state where I fail at:
```
 OpenFAST input file heading:
     FAST Certification Test #01: NREL 5.0 MW Baseline Wind Turbine (Onshore)

  Running ElastoDyn.
 Nodal outputs section of ElastoDyn input file not found or improperly formatted.
  Running AeroDyn.
 Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 1)
 Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 2)
 Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 3)
 Using uniform blade force node clustering.
  Running ServoDyn.
  Running ServoDyn Interface for Bladed Controllers (using GNU Fortran for Linux).
 Using legacy Bladed DLL interface.
turbineData[iTurb].inflowType = 2
turbineData[iTurbLoc].inflowType 2
turbineData[iTurbLoc].numForcePtsTwr = 20
turbineData[iTurbLoc].numForcePtsBlade = 50
turbineData[iTurbLoc].numForcePts = 171
nvelpts = 35
nfpts = 171  50 20
nvelpts = 35
nfpts = 171  50 20
nvelpts = 35
nfpts = 171  50 20
nvelpts = 35
nfpts = 171  50 20
naluX: putget.m4:745: putNCvx_double_double: Assertion `value != NULL' failed.
[1]    409417 abort (core dumped)  ../../../naluX -i  -o nrel5MWactuatorLine.log
```

Not sure how to proceed next.

**Comment by marchdf** [comment]
This actually solves broken `ActuatorBulkFastTests` so I might push for  merging this.

**Comment by marchdf** [comment]
Let's merge this and see if it fixes the tests. A debug run was successful. But it's unclear what happened to the segfault I was seeing... Maybe a different openfast version?

**Review by jrood-nrel — APPROVED** [review]

**Pull request merged**
