### PR TITLE
Changed default value of heightMultiplier_ to 1.0e6

### PR DESCRIPTION
**Pull request by lawrenceccheung**
**Pull-request type:**
- [X] Bug fix 
- [ ] Documentation update
- [ ] Feature enhancement

## Description of the pull-request
Addresses problem seen in [issue 509](https://github.com/Exawind/nalu-wind/issues/509).

Changed the default value of `heightMultiplier_` to `1.0e6` in `BdyHeightAlgorithm.h`.  Tested on a number of different ABL meshes, and this default value should work without having to change it on input.

Additional documentation should be provided in the future detailing the impacts of `heightMultiplier_` on the ABL statistics.

## Checklist

**NOTE** The checklist below is a suggestion and not mandatory. You don't have
to _check all boxes_ to submit a pull request. However, please add a brief
explanation in your pull request summary explaining the omission for the benefit
of reviewers and developers.

*All pull requests*
- [X] Builds successfully (*must test on at least one system/compiler combination*)
  - Operating systems 
    - [X] Linux
    - [ ] MacOS
  - Compilers 
    - [ ] GCC
    - [ ] LLVM/Clang
    - [X] Intel compilers
    - [ ] NVIDIA CUDA
- [X] Compiles without warnings
- [X] Passes all unit tests
- [X] Passes all regression tests
- [ ] Documentation builds without errors

*For new code updates*
- [ ] Documentation updates - additions to user, theory, and verification manuals
- [ ] New unit tests providing coverage for new code, bug fixes etc.
- [ ] New regression tests exercising the new code

### CODE REVIEW

**Comment by sayerhs** [comment]
@lawrenceccheung Do you want to take a stab at updating documentation also?

**Comment by lawrenceccheung** [comment]
@sayerhs  Yeah, I can try adding some documentation.  I actually don't see anything at all about `boundary_layer_statistics` in [nalu_inp.rst](https://github.com/Exawind/nalu-wind/blob/master/docs/source/user/nalu_run/nalu_inp.rst), so let me start with that.

**Comment by sayerhs** [comment]
@lawrenceccheung Please update https://github.com/Exawind/nalu-wind/blob/5f0509bd03ad9b1cc64299416684384637e94a7d/src/wind_energy/BdyHeightAlgorithm.C#L69 to this

```C++
const uint64_t htInt = static_cast<uint64_t>(std::round(ht * heightMultiplier_));
```

So that we don't end up with integer overflows when using `heightMultiplier_ = 1.e06`.

**Comment by lawrenceccheung** [comment]
@sayerhs Just made the `uint64_t` change and also added some boundary_layer_statistics documentation in the latest commit.

**Pull request merged**
