### PR TITLE
A small unit test that fails in Kokkos::parallel_reduce.

### PR DESCRIPTION
**Pull request by overfelt**
I think this test should not throw an exception but
reducing over a zero length loop leads to a memory
access error.

It is not clear if this is a nalu, stk or kokkos problem.

### CODE REVIEW

**Review by alanw0 — COMMENTED** [review]
This looks like a good test. But I'm not sure if I'm correctly interpreting how you say it fails. Can it "expect" wrong behavior to be a passing test until it is fixed? I would hesitate to push in a crashing test...

**Comment by overfelt** [comment]
@alanw0   No, this should not be merged, it is for example purposes only for discussion.  There is an expect-throw construct in gtest but then fixing the problem would cause the test to fail which is no good.  I managed to reduce the example to Kokkos only code and submitted a ticket to the Kokkos repository so it seems stk is off the hook.

**Comment by alanw0** [comment]
@overfelt sounds good, thanks!

**Comment by jhux2** [comment]
@overfelt Is this part of a larger Kokkos refactor?  The file `packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp` doesn't seem to exist in Trilinos develop.  It would be nice to be able to do a "hot-fix" without having to wait for another Kokkos promotion.

**Comment by overfelt** [comment]
The Kokkos pull request is to the develop branch of Kokkos which has a Kokkos_Cuda_Parallel_Team.hpp file for which the fix will be applied.  The Kokkos master branch does not have this file as yet.   But Kokkos_Cuda_Parallel_Team.hpp  was created from Kokkos_Cuda_Parallel.hpp and if you hunt through this file you can find the same lines of code as were patched in the pull request.  Not an ideal solution but I don't have a better suggestion.

**Comment by jhux2** [comment]
@overfelt Thank you for tracking this down and submitting a reproducer to Kokkos!  The Kokkosk patch should help clean up the Nalu-Wind dashboard and address #973.

**Pull request closed without merging**
