### PR TITLE
Output absolute and relative diffs for failing tests

### PR DESCRIPTION
**Pull request by sayerhs**
The behavior of `pass_fail.sh` is modified such that it reports both the
absolute difference (original behavior) and the corresponding relative
difference for failing tests.

In addition, it also introduces a few other modifications:

- Add padding between the test name and the timing outputs
- Refactor the code that uses `bc` for doing calculations
- Fix an issue where the script was computing diffs of timestep count and  timestep size

### CODE REVIEW

**Comment by sayerhs** [comment]
This pull request addresses @lucbv's comment in #255. The `Mean system norm` output in Nalu-Wind only outputs 16 digits, so there might not be enough precision if the mean norms are large values to start with. Example output from the new script

```
$ grep -i "FAIL:" Testing/Temporary/LastTest.log |sort
FAIL: ablNeutralEdge..........................    29.4211s 3.4543e-11 1.2186e-08
FAIL: ablNeutralEdgeSegregated................    25.4344s 5.1439e-11 2.2761e-08
FAIL: ablStableElem...........................    25.6910s 1.8252e-11 9.2726e-09
FAIL: ablUnstableEdge.........................    25.7376s 2.0428e-11 3.7749e-09
FAIL: ablUnstableEdge_ra......................    13.1441s 3.8280e-12 2.4838e-12
FAIL: airfoilRANSEdge.........................     3.4053s 1.4700e-08 2.2836e-14
FAIL: dgNonConformalFluidsEdge................    17.4894s 6.4000e-13 2.6206e-14
FAIL: ekmanSpiral.............................     4.7124s 1.3950e-15 3.3145e-13
FAIL: elemClosedDomain........................     1.1247s 6.1215e-09 2.1855e-08
FAIL: fluidsPmrChtPeriodic....................    40.1020s 1.2029e-12 1.6486e-12
FAIL: heatedWaterChannelEdge..................     5.7586s 5.8439e-08 2.3620e-09
FAIL: heliumPlume_rst.........................    59.8219s 4.5000e-14 3.0174e-14
FAIL: karmanVortex............................     0.4153s 1.1800e-15 1.2575e-14
FAIL: movingCylinder..........................     3.8665s 1.3120e-12 1.3114e-12
```

**Comment by lucbv** [comment]
@sayerhs I would approve but I can't, thanks for looking into this!
Also I would like to note that for some tests we use python scripts (see `norms.py` in hoVortex_P2 example) to check the pass/fail status and for others we use `pass_fail.sh`. I would be in favour of removing completely `pass_fail.sh` in favour of a new `pass_fail.py` but that's outside of the scope of this PR...

**Comment by jrood-nrel** [comment]
@lucbv I sent you an invite to the github team so you can review PRs.

**Comment by lucbv** [comment]
@jrood-nrel thanks!

**Comment by sayerhs** [comment]
I agree with the preference for python script, but until we have python3 available by default on all machines it is not ideal. And no, pulling python via spack is not appealing to me. :)

Right now the `norms.py` has some python2 specific syntax which cause it to fail on python3, so a general cleanup is required.

**Pull request merged**
