### PR TITLE
Extend unit test to include some Edge Master Element checking.

### PR DESCRIPTION
**Pull request by overfelt**
Seems a bit complicated to use the face/edge combination scratchview in this unit test. Maybe this is not the best example of this kind of thing.

### CODE REVIEW

**Comment by alanw0** [comment]
Yes, I'm having trouble thinking about a better way to do this kind of stuff right now...

**Comment by sayerhs** [comment]
@overfelt Any reason to wait on merging this one?

**Comment by overfelt** [comment]
Oh, forgot about this.  I think the unit test should still work and it does provide a tiny bit of checking for one of the master element functions.  So, yes, let's merge.

**Comment by sayerhs** [comment]
Seems to be addressed in #422

**Pull request closed without merging**
