### PR TITLE
Sideset writer that doesn't require transfers

### LINKED ISSUE #859: Extract surface data during run
Its would be great to be able to extract the surface data and geometry on specified boundaries during a run at much higher frequencies compared to the full field output. This would help calculation of load profiles on blades at much higher frequencies. The geometry information could be optimized for rigid body rotation runs, but would be necessary at the same frequency for FSI runs.

### PR DESCRIPTION
**Pull request by psakievich**
**Pull-request type:**
- [ ] Bug fix 
- [ ] Documentation update
- [x] Feature enhancement

## Description of the pull-request

Add a sideset writer option to nalu-wind that doesn't require transfers.  Thanks to @rcknaus for putting the utility together.  I've tested this on the ellipse problem and it works well. Resolves #859.  Removes need for #874 and also #870.  However it would still be best to have the stk team put this functionality into stk for an optimized long term solution as noted in the comments of #870.

## Checklist

**NOTE** The checklist below is a suggestion and not mandatory. You don't have
to _check all boxes_ to submit a pull request. However, please add a brief
explanation in your pull request summary explaining the omission for the benefit
of reviewers and developers.

*All pull requests*
- [x] Builds successfully (*must test on at least one system/compiler combination*)
  - Operating systems 
    - [x] Linux
    - [ ] MacOS
  - Compilers 
    - [x] GCC
    - [ ] LLVM/Clang
    - [ ] Intel compilers
    - [ ] NVIDIA CUDA
- [x] Compiles without warnings
- [x] Passes all unit tests
- [ ] Passes all regression tests
- [ ] Documentation builds without errors

*For new code updates*
- [ ] Documentation updates - additions to user, theory, and verification manuals
- [x] New unit tests providing coverage for new code, bug fixes etc.
- [ ] New regression tests exercising the new code

### CODE REVIEW

**Comment by psakievich** [comment]
@jrood-nrel looks like the Trilinos version being used by the CI isn't current.

**Comment by jrood-nrel** [comment]
Yeah the docker images needs to be updated.

**Comment by psakievich** [comment]
Anyone want to comment on this? the CI is broken for now.  I'd like to merge this unless anyone has issues.

**Review by rcknaus — APPROVED** [review]
Looks good. May want to modify a regression test to use this capability as well.

**Comment by psakievich** [comment]
@rcknaus good point. I've added to a regression test. We can also use this feature to output precursor planes for abl simulations.

**Pull request merged**
