### PR TITLE
Add option to dump mesh on failed jacobian check

### PR DESCRIPTION
**Pull request by psakievich**

### CODE REVIEW

**Comment by psakievich** [comment]
@alanw0 will this be parallel consistent?  Looking at it now, I think not.

**Comment by psakievich** [comment]
I think I fixed it.

**Comment by alanw0** [comment]
@psakievich I'm having trouble figuring out if it's parallel consistent. You want to call provide_output on every mpi rank, but it looks like impl_negative_jacobian_check only throws on ranks where it finds a negative volume. I'm having trouble seeing where there's an allreduce to make the result of impl_negative_jacobian_check global. If that's in there, then it's all good.

**Comment by psakievich** [comment]
@alanw0 ah you are right. Still need the all-reduce

**Review by gantech — APPROVED** [review]

**Review by alanw0 — COMMENTED** [review]
Looks good.

**Pull request merged**
