### PR TITLE
Turbulent Kinetic Energy Wall Algorithm for ngp.

### PR DESCRIPTION
**Pull request by overfelt**
This passes the unit test but I'm not sure it is all correct.  The use of parallel_sum seems to be odd  for a single processor run but it was the only way I could get non-zero values out of the algorithm.

### CODE REVIEW

**Comment by sayerhs** [comment]
@overfelt Seems like there was some serious miscommunication here. Thsi algorithm has already been converted here: https://github.com/Exawind/nalu-wind/blob/f8fb51a40cdd27100be35e92a7184b868eebda66/src/ngp_algorithms/TKEWallFuncAlg.C#L26

**Comment by overfelt** [comment]
@sayerhs, I had checked it off on #336 but I guess I was too slow in getting it converted. 

So why do we have to add the coordinates field to the faceData_ requests when they are not used?

**Comment by sayerhs** [comment]
I am sorry @overfelt I think I mistakenly assumed that I had checked it off. WE should have added names to people who had checked things off. It is my mistake. I'll try to be more careful in future. Regarding `coordinates`, good catch! While I was developing, I had registered `shape_fcn` for some reason and then took it out, but forgot to take `coordinates` out when I was cleaning up the code.

**Comment by overfelt** [comment]
I thought that if I checked off a box way down the list I could get ahead of you, but you are too fast.  

Another question:  Why do you have to sync to host before the parallel_sum but don't have to sync_to_device afterwards?  Is that done automatically by one of the following functions?  

And does the stk function ngp::parallel_sum() not work?  I see that it just does a sync-to-host/parallel_sum/sync-to-device but when I tried it it simply did not seem to work for me.  Maybe @alanw0 can comment on that.

jro

**Comment by sayerhs** [comment]
@overfelt That is a bug in the code that I need to fix. The parallel update logic needs to change also, to incorporate Alan's latest updates. One thing we need to figure out is the best way to minimize device-host-device transfers. Right now every call to `ngp::parallel_*` method will force a sync.

**Comment by alanw0** [comment]
I'm interested to hear any further details about the parallel update logic. Functions are in place to do parallel_sum, copy_owned_to_shared and communicate_field_data for ngp::Fields. As Shreyas says, we may still need to reduce the sync_to_host/sync_to_device calls, but as far as I know those functions are working.

**Pull request closed without merging**
