### PR TITLE
Fix memory leak in FixPressureAtNodeAlgorithm.

### PR DESCRIPTION
**Pull request by alanw0**

### CODE REVIEW

**Comment by alanw0** [comment]
@sayerhs would a unique_ptr survive being copied into the lambda of the parallel_for (for the cpu case)?

**Comment by sayerhs** [comment]
Hmm... I forgot that `KOKKOS_LAMBDA` does `[=]`, so obviously that won't work. Why does `get_coeff_applier` return a pointer? Can it return an object, that can be moved? Either way, just curiosity on my part. Don't let this hold up the pull request.

**Comment by overfelt** [comment]
Just curious:
1. Is the coeffApplyer/deviceCoeffApplier pattern inside of a ifdef KOKKOS_ENABLE_CUDA the long term solution or just a short term thing until all CoeffAppliers are device compatable?
2. Alan, you are going to fix the other translation units with the free inside the ifdef?

**Comment by sayerhs** [comment]
@overfelt Good point regarding (1), I think there should be an implementation of `device_pointer()` for HostOnlyCoeffApplier too. So that we don't have additional `#ifdef`s further down. 

Another thing of concern is that #233 is now proliferating to more algorithms

**Comment by alanw0** [comment]
Dammit, you guys are both raising good points. Regarding 1., I agree there needs to be some cleanup to eliminate the ifdefs. Regarding James' point 2., the other occurrences aren't currently leaks because both the creation and the deletion are inside ifdefs due to the fact that the non-cuda usage still goes through the traditional apply_coeff(..) function instead of the coeffApplier. So it needs unification, but it's not a leak.
Finally, @sayerhs I agree that needs to be cleaned up. I'll look at how to clean up the save-off-diagonal feature so that this isn't a bifurcation point for that.

I'll go ahead and merge this leak-fix now, but make these cleanups next on my to-do list.

**Pull request merged**
