### PR TITLE
Add modify_on_host calls in SurfaceForceAndMoment...

### PR DESCRIPTION
**Pull request by alanw0**
These ones are necessary to get the airfoilRANSEdgeTrilinos
case to run without crashing on GPU.

**Pull-request type:**
- [x] Bug fix 
- [ ] Documentation update
- [ ] Feature enhancement

## Description of the pull-request

*Provide a description of your proposed changes. If there is a related issue, please specify.**

## Checklist

**NOTE** The checklist below is a suggestion and not mandatory. You don't have
to _check all boxes_ to submit a pull request. However, please add a brief
explanation in your pull request summary explaining the omission for the benefit
of reviewers and developers.

*All pull requests*
- [x] Builds successfully (*must test on at least one system/compiler combination*)
  - Operating systems 
    - [x] Linux
    - [ ] MacOS
  - Compilers 
    - [x] GCC
    - [ ] LLVM/Clang
    - [ ] Intel compilers
    - [x] NVIDIA CUDA
- [ ] Compiles without warnings
- [ ] Passes all unit tests
- [ ] Passes all regression tests
- [ ] Documentation builds without errors

*For new code updates*
- [ ] Documentation updates - additions to user, theory, and verification manuals
- [ ] New unit tests providing coverage for new code, bug fixes etc.
- [ ] New regression tests exercising the new code

### CODE REVIEW

**Comment by sayerhs** [comment]
@alanw0 Do you remember where these fields are accessed on device?

**Comment by alanw0** [comment]
@sayerhs no, but I'll find it again and let you know.

**Comment by alanw0** [comment]
@sayerhs Hmm, hold off on merging this. I now can't find any evidence that those fields are used on device.
I had another couple of commits which I thought were not important and/or not push-worthy, let me do some reverting in different combinations and figure out what I'm actually doing.

**Comment by alanw0** [comment]
As far as I can tell, these changes are not necessary. Closing.

**Pull request closed without merging**
