### PR TITLE
Luc: changing sln and rhs from Vector to MultiVector

### PR DESCRIPTION
**Pull request by lucbv**
This is the first step to introduce the TpetraSegergatedLinearSystem.
This will allow to store the solution and rhs correctly.

This is still a work in progress, I will run some checks first before asking for this to be merged.

@sayerhs is there a specific suite of builds/tests that I need to perform before merging something in?

### CODE REVIEW

**Comment by lucbv** [comment]
Adding @jhux2 so he can follow progress...

**Comment by sayerhs** [comment]
@lucbv All the regression tests should succeed with this change, so you can pick any of the non-Hypre tests and try them to make sure this change didn't affect anything.

**Comment by rcknaus** [comment]
The code looks good to me.  Checking for the regression test suite that there isn't any real performance change here would be good too.

**Comment by lucbv** [comment]
Now that my build create the unit-test executable I can tell that they pass fine:
```
[----------] Global test environment tear-down
[==========] 317 tests from 68 test cases ran. (125313 ms total)
[  PASSED  ] 317 tests.
```

I am also attaching results from the `dgNonConformalThreeBlade` these were run on my workstation so the timing are not that accurate but everything else looks fine and performance should not take any hit as `Tpetra::Vector` really inherits most of `Tpetra::MultiVector`.
Eventually we absolutely need the `Tpetra::MultiVector` anyway...
[dgNonConformalThreeBlade.log](https://github.com/Exawind/nalu-wind/files/3288088/dgNonConformalThreeBlade.log)
[dgNonConformalThreeBlade_lucbv.log](https://github.com/Exawind/nalu-wind/files/3288089/dgNonConformalThreeBlade_lucbv.log)

**Comment by alanw0** [comment]
@lucbv  did you run the nightly tests using ctest? That's the way to see if all the tests are passing.
I usually use a command like this: % ctest -j16 --output-on-failure
(Prehaps you already did this, I just couldn't tell from your comments since you were talking about a specific test...)

**Comment by lucbv** [comment]
@alanw0 I went with @sayerhs suggestion:

> you can pick any of the non-Hypre tests and try them to make sure this change didn't affect anything

but if that is not the proper requirement then I can run ctest instead, I just need to know what the standard?

**Comment by alanw0** [comment]
@lucbv I see that you attached a couple of log files, but I wasn't sure if you ran that test with ctest. What ctest does is check the norms in the log file against pre-recorded gold norms using a tolerance.
In any case, we expect all code changes to pass all tests. This does get checked by the nightly dashboard process, so bad commits can be identified and/or reverted, but it's so easy to just check the tests before pushing. You don't have to check the tests on every platform that the nightly dashboard checks, but it's generally prudent to check at least 1 platform.

**Comment by lucbv** [comment]
@alanw0 I understand and that is what I usually do for trilinos except it does not seem to really work well with Nalu...
I pulled in the mesh repo to try the ctest command but it somehow does not find the mesh files I am guessing that this is due to the location of the input file relative to the mesh file or relative to where ctest is invoked?
Anyhow it does not seem to work properly.

**Comment by alanw0** [comment]
@lucbv I'm puzzled by why it isn't working for you. The things I do are as follows.
Use git clone --recursive to get nalu-wind. That brings the mesh submodule along for the ride.
Create a 'build' subdirectory within the nalu-wind clone, and build using the 'nalu-wind-gcc.sh' script provided by Shreyas' exawind-builder infrastructure. (You first have to build trilinos etc., but you're obviously doing that.) anyway, once nalu-wind builds, then running ctest in that build directory should find everything successfully.

**Comment by lucbv** [comment]
@alanw0 I did not use the "--recursive" option with git which might actually be the reason for my troubles... I will try that and report back. I am building with my own scripts but I assume that since my build finishes correctly, my scripts are not so bad? I developed them to use seems compatible modules.

**Comment by sayerhs** [comment]
@lucbv Just a couple of things to add to @alanw0's comments. If you forgot to use `--recursive` option during the initial clone you can still get the mesh files by explicitly invoking submodule commands

```
git submodule init && git submodule update
```

then check that the mesh files are showing up when you `cd reg_tests/mesh; ls`

Finally, if you still see errors, please run 

```
ctest --output-on-failure -R ablNeutralEdge
```
and share the output so that we can further debug this. I am wondering if there is an issue with the parallel-netcdf that you ended up using that is not reading files properly. We have had that issue crop up when using system modules on Cori etc. I haven't tried the SEMS modules, so I am not confident about them.

**Comment by lucbv** [comment]
@sayerhs here is the type of error I am seeing when running the `ablNeutralEdge` problem:

```
Exodus Library Warning/Error: [ex_open_int]
	ERROR: failed to open ../../mesh/abl_5km_5km_1km_neutral.g.8.1 of type 0 for reading. Either the file does not exist, or there is a permission or file format issue.

Exodus Library Warning/Error: [ex_open_int]
	ERROR: failed to open ../../mesh/abl_5km_5km_1km_neutral.g.8.2 of type 0 for reading. Either the file does not exist, or there is a permission or file format issue.

Exodus Library Warning/Error: [ex_open_int]
	ERROR: failed to open ../../mesh/abl_5km_5km_1km_neutral.g.8.3 of type 0 for reading. Either the file does not exist, or there is a permission or file format issue.

Exodus Library Warning/Error: [ex_open_int]
	ERROR: failed to open ../../mesh/abl_5km_5km_1km_neutral.g.8.4 of type 0 for reading. Either the file does not exist, or there is a permission or file format issue.

Exodus Library Warning/Error: [ex_open_int]
	ERROR: failed to open ../../mesh/abl_5km_5km_1km_neutral.g.8.5 of type 0 for reading. Either the file does not exist, or there is a permission or file format issue.

Exodus Library Warning/Error: [ex_open_int]
	ERROR: failed to open ../../mesh/abl_5km_5km_1km_neutral.g.8.6 of type 0 for reading. Either the file does not exist, or there is a permission or file format issue.

Exodus Library Warning/Error: [ex_open_int]
	ERROR: failed to open ../../mesh/abl_5km_5km_1km_neutral.g.8.7 of type 0 for reading. Either the file does not exist, or there is a permission or file format issue.

Exodus Library Warning/Error: [ex_open_int]
	ERROR: failed to open ../../mesh/abl_5km_5km_1km_neutral.g.8.0 of type 0 for reading. Either the file does not exist, or there is a permission or file format issue.
ERROR: Unable to open input exodus decomposed database files:
	../../mesh/abl_5km_5km_1km_neutral.g.8.0
	../../mesh/abl_5km_5km_1km_neutral.g.8.1
	../../mesh/abl_5km_5km_1km_neutral.g.8.2
	../../mesh/abl_5km_5km_1km_neutral.g.8.3
	../../mesh/abl_5km_5km_1km_neutral.g.8.4
	../../mesh/abl_5km_5km_1km_neutral.g.8.5
	../../mesh/abl_5km_5km_1km_neutral.g.8.6
	../../mesh/abl_5km_5km_1km_neutral.g.8.7

terminate called after throwing an instance of 'std::runtime_error'
  what():  Expr '!(Teuchos::is_null(m_database) || !m_database->ok(true))' eval'd to true, throwing.
Error occured at: stk_io/stk_io/InputFile.cpp:147
Error: ERROR: Could not open database '../../mesh/abl_5km_5km_1km_neutral.g' of type 'exodus'
```

It could be related to `parallel-netcdf` or `hdf5` I guess, but somehow after manually copying files in the right location for `dgNonConformalThreeBlades`, I am able to run that test... Any thoughts?

**Comment by lucbv** [comment]
Actually looking at it closer, I notice that I have 5 mesh files for dgNonConformalThreeBlades, the serial file (ending in .g) and 4 decomposed files (ending in .g.4.n). That is not the case of the ablNeutral problem and I am wondering if this is the issue, in which case I might have to first decompose the mesh into parallel files and then run the simulation?
I do not know how to generate the parallel mesh inputs?

**Comment by sayerhs** [comment]
@lucbv OK. This is what I suspected, and it is an issue with `parallel-netcdf + netcdf` that is being linked during Trilinos build. I am pretty sure if you did 

```
ctest -R dgNonConformalThreeBlade
```

it will work fine. The difference between the two meshes `ncdump -h`

```
# dgNonConformalThreeBlade mesh
// global attributes:
		:api_version = 4.57f ;
		:version = 4.57f ;
		:floating_point_word_size = 8 ;
		:file_size = 0 ;
		:title = "cubit(/Users/spdomin/Desktop/newThreeBlade.g): 08/26/2010: 15:47:44" ;

# ablNeutralEdge mesh

// global attributes:
		:api_version = 7.03f ;
		:version = 7.03f ;
		:floating_point_word_size = 8 ;
		:file_size = 1 ;
		:int64_status = 7168 ;
		:title = "Sierra Output Default Title" ;
		:maximum_name_length = 13 ;
		:last_written_time = 0. ;
```

is the `int64_status` flag, which seems to require specific netcdf/parallel-netcdf for reading it. @alanw0 Can you find out why this is an issue with Greg or someone else?

**Comment by sayerhs** [comment]
@lucbv the input files contain `automatic_decomposition_type: rcb` that instructs that the files will be automatically decomposed upon read. You can manually decompose the mesh by using the `decomp` command in Trilinos `build` directory, if you used the standard CMake configure for Trilinos that enables IOSS/SEACAS utilities ([see here](https://github.com/sayerhs/exawind-builder/blob/master/codes/trilinos.bash#L116)).

**Comment by lucbv** [comment]
@sayerhs using the `decomp` script from `seacas` I was able to decompose the mesh for `ablNeutralEdge` and subsequently run the test as follows: `ctest -R ablNeutralEdge -VV `.
Using nalu/master I get the following:
```
$ ctest -R ablNeutralEdge -VV
UpdateCTestConfiguration  from :/home/lberge/Research/codes/ExaWind/nalu_build/reg_tests/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/lberge/Research/codes/ExaWind/nalu_build/reg_tests/DartConfiguration.tcl
Test project /home/lberge/Research/codes/ExaWind/nalu_build/reg_tests
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: ablNeutralEdge

1: Test command: /usr/bin/sh "-c" "/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/bin/mpiexec -n 8  /home/lberge/Research/codes/ExaWind/nalu_build/naluX  -i /ascldap/users/lberge/Research/codes/ExaWind/nalu_lucbv/reg_tests/test_files/ablNeutralEdge/ablNeutralEdge.i -o ablNeutralEdge.log && /ascldap/users/lberge/Research/codes/ExaWind/nalu_lucbv/reg_tests/pass_fail.sh ablNeutralEdge /ascldap/users/lberge/Research/codes/ExaWind/nalu_lucbv/reg_tests/test_files/ablNeutralEdge/ablNeutralEdge.norm.gold 0.000000000000001"
1: Test timeout computed to be: 1500
1: IOSS: Input database contains 8-byte integers. Setting Ioss to use 8-byte integers.
1: ablNeutralEdge                      FAILED:   114.5805 s max-diff: 6.098180e-04
1/1 Test #1: ablNeutralEdge ...................***Failed  115.95 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
regression    = 927.61 sec*proc (1 test)

Total Test time (real) = 115.96 sec

The following tests FAILED:
	  1 - ablNeutralEdge (Failed)
Errors while running CTest
```
using my work branch I get similar output:
```
$ ctest -R ablNeutralEdge -VV
UpdateCTestConfiguration  from :/home/lberge/Research/codes/ExaWind/nalu_build/reg_tests/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/lberge/Research/codes/ExaWind/nalu_build/reg_tests/DartConfiguration.tcl
Test project /home/lberge/Research/codes/ExaWind/nalu_build/reg_tests
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: ablNeutralEdge

1: Test command: /usr/bin/sh "-c" "/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/bin/mpiexec -n 8  /home/lberge/Research/codes/ExaWind/nalu_build/naluX  -i /ascldap/users/lberge/Research/codes/ExaWind/nalu_lucbv/reg_tests/test_files/ablNeutralEdge/ablNeutralEdge.i -o ablNeutralEdge.log && /ascldap/users/lberge/Research/codes/ExaWind/nalu_lucbv/reg_tests/pass_fail.sh ablNeutralEdge /ascldap/users/lberge/Research/codes/ExaWind/nalu_lucbv/reg_tests/test_files/ablNeutralEdge/ablNeutralEdge.norm.gold 0.000000000000001"
1: Test timeout computed to be: 1500
1: IOSS: Input database contains 8-byte integers. Setting Ioss to use 8-byte integers.
1: ablNeutralEdge                      FAILED:   114.4345 s max-diff: 6.098180e-04
1/1 Test #1: ablNeutralEdge ...................***Failed  115.84 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
regression    = 926.70 sec*proc (1 test)

Total Test time (real) = 115.85 sec

The following tests FAILED:
	  1 - ablNeutralEdge (Failed)
Errors while running CTest
```

It is good to know that I can decompose the tests manually if needed but it would be nicer to have it done automatically.

**Comment by alanw0** [comment]
I've sent a query to Greg Sjaardema and pointed him to this page in case he has insight about what might be the issue.

**Comment by alanw0** [comment]
I got the following reply from Greg:

```
The mesh indicates that it is storing all integer data as 64-bit integers. This
is netcdf-4 format which requires that the HDF5 capability be available.  You
can try running “exo_format -c” to see what options were available on the
build (or io_info –config).  This assumes a fairly recent version of Trilinos…

Can also run ‘exo_format {filename}’ to find out more information about the mesh.

..Greg
```

**Comment by sayerhs** [comment]
Thanks @alanw0. @lucbv here is the configuration output from my builds

```bash
$ ~/exawind/install/gcc/trilinos/bin/io_info --config

Supported database types:
	catalyst dof dof_exodus exodus exodusII exodusii gen_struc generated genesis heartbeat

Third-Party Library Configuration Information:

	Exodus Version 7.19
		Parallel enabled
		Thread Safe NOT enabled
		Deprecated Functions available

	NetCDF Version 4.6.1
		CDF5 enabled
		HDF5 enabled (1.10.4)
		parallel IO enabled via HDF5 and/or PnetCDF
		parallel IO enabled via PnetCDF (1.8.0 of 19 Dec 2016)
		ERANGE_FILL support
		NC_HAVE_META_H defined
		API Version 2 support enabled
```

**Comment by gsjaardema** [comment]
It sounds like the `automatic_decomposition_type = rib` is not being parsed for some reason.  The IOSS library is not being told to do the decomposition which is why it is looking for the individual file-per-processor files.  Based on the configuration output, the parallel capability is enabled and the NetCDF-4 capability is enabled which are both correct.  Not sure why the automatic decomposition isn't being handled correctly...

**Comment by sayerhs** [comment]
@gsjaardema Sorry for the confusion, the configuration I posted was on a system where I can confirm that the file is being read correctly, i.e., the desired build. I was just posting the output so that @lucbv could compare with the output on the system where he is seeing the error (posted above).

**Comment by lucbv** [comment]
@sayerhs @gsjaardema here is what I get from io_info:

```
$ ./install/trilinos/bin/io_info --config

Supported database types:
	catalyst exodus exodusII exodusii gen_struc generated genesis heartbeat 

Third-Party Library Configuration Information:

	Exodus Version 7.20
		Parallel NOT enabled
		Thread Safe NOT enabled
		Deprecated Functions available

	NetCDF Version 4.4.1
		HDF5 enabled (1.8.12)
		NC_HAVE_META_H defined
		API Version 2 support enabled
```
I am guessing that there is an issue with parallel IO?
As an fyi this is what my Trilinos configuration looks like:
```
cmake \
-DCMAKE_INSTALL_PREFIX="${trilinos_install_dir}" \
-DTrilinos_ENABLE_CXX11=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-DTpetra_INST_DOUBLE:BOOL=ON \
-DTpetra_INST_INT_LONG:BOOL=ON \
-DTpetra_INST_COMPLEX_DOUBLE=OFF \
-DTrilinos_ENABLE_TESTS:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF \
-DTPL_ENABLE_MPI=ON \
-DMPI_BASE_DIR:PATH="${mpi_base_dir}" \
-DTPL_ENABLE_SuperLU=OFF \
-DTrilinos_ENABLE_Epetra:BOOL=OFF \
-DTrilinos_ENABLE_Tpetra:BOOL=ON \
-DTrilinos_ENABLE_ML:BOOL=OFF \
-DTrilinos_ENABLE_MueLu:BOOL=ON \
-DTrilinos_ENABLE_EpetraExt:BOOL=OFF \
-DTrilinos_ENABLE_AztecOO:BOOL=OFF \
-DTrilinos_ENABLE_Belos:BOOL=ON \
-DTrilinos_ENABLE_Ifpack2:BOOL=ON \
-DTrilinos_ENABLE_Amesos2:BOOL=ON \
-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
-DTrilinos_ENABLE_Ifpack:BOOL=OFF \
-DTrilinos_ENABLE_Amesos:BOOL=OFF \
-DTrilinos_ENABLE_Zoltan:BOOL=ON \
-DTrilinos_ENABLE_STKMesh:BOOL=ON \
-DTrilinos_ENABLE_STKSimd:BOOL=ON \
-DTrilinos_ENABLE_STKIO:BOOL=ON \
-DTrilinos_ENABLE_STKTransfer:BOOL=ON \
-DTrilinos_ENABLE_STKSearch:BOOL=ON \
-DTrilinos_ENABLE_STKUtil:BOOL=ON \
-DTrilinos_ENABLE_STKTopology:BOOL=ON \
-DTrilinos_ENABLE_STKUnit_tests:BOOL=ON \
-DTrilinos_ENABLE_STKUnit_test_utils:BOOL=ON \
-DTrilinos_ENABLE_Gtest:BOOL=ON \
-DTrilinos_ENABLE_STKClassic:BOOL=OFF \
-DTrilinos_ENABLE_SEACASExodus:BOOL=ON \
-DTrilinos_ENABLE_SEACASEpu:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodiff:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemspread:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemslice:BOOL=ON \
-DTrilinos_ENABLE_SEACASIoss:BOOL=ON \
-DTPL_ENABLE_Netcdf:BOOL=ON \
-DNetCDF_ROOT:PATH="${netcdf_install_dir}" \
-DTPL_ENABLE_HDF5:BOOL=ON \
-DHDF5_ROOT:PATH="${hdf_install_dir}" \
-DHDF5_NO_SYSTEM_PATHS=ON \
-DZlib_ROOT:PATH="${z_install_dir}" \
-D Boost_INCLUDE_DIRS="${SEMS_BOOST_ROOT}/include" \
-D Boost_LIBRARY_DIRS="${SEMS_BOOST_ROOT}/lib" \
-D BoostLib_INCLUDE_DIRS="${SEMS_BOOST_ROOT}/include" \
-D BoostLib_LIBRARY_DIRS="${SEMS_BOOST_ROOT}/lib" \
-DTrilinos_ASSERT_MISSING_PACKAGES=OFF \
$EXTRA_ARGS \
$trilinos_source_dir
```

**Comment by sayerhs** [comment]
@lucbv The following are the lines from [my trilinos config](https://github.com/sayerhs/exawind-builder/blob/master/codes/trilinos.bash#L131)

```
            -DTPL_ENABLE_Netcdf:BOOL=ON
            -DNetCDF_ROOT:PATH=${NETCDF_ROOT_DIR}
            -DTPL_Netcdf_PARALLEL:BOOL=ON
            -DTPL_Netcdf_Enables_Netcdf4:BOOL=ON
            -DTPL_ENABLE_Pnetcdf:BOOL=ON
            -DPNetCDF_ROOT:PATH=${PARALLEL_NETCDF_ROOT_DIR}
            -DTPL_ENABLE_HDF5:BOOL=ON
            -DHDF5_ROOT:PATH=${HDF5_ROOT_DIR}
            -DHDF5_NO_SYSTEM_PATHS:BOOL=ON
```

Hopefully, @gsjaardema can chime in with which of these options you'll have to turn on in your config.

**Comment by lucbv** [comment]
@sayerhs @gsjaardema 
Alright, I am now using the following Trilinos configuration:
```
cmake \
    -DCMAKE_INSTALL_PREFIX="${trilinos_install_dir}" \
    -DTrilinos_ENABLE_CXX11=ON \
    -DCMAKE_BUILD_TYPE=RELEASE \
    -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -DTpetra_INST_DOUBLE:BOOL=ON \
    -DTpetra_INST_INT_LONG:BOOL=ON \
    -DTpetra_INST_COMPLEX_DOUBLE=OFF \
    -DTrilinos_ENABLE_TESTS:BOOL=OFF \
    -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
    -DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF \
    -DTPL_ENABLE_MPI=ON \
    -DMPI_BASE_DIR:PATH="${SEMS_OPENMPI_ROOT}" \
    -DTPL_ENABLE_SuperLU=OFF \
    -DTrilinos_ENABLE_Epetra:BOOL=OFF \
    -DTrilinos_ENABLE_Tpetra:BOOL=ON \
    -DTrilinos_ENABLE_ML:BOOL=OFF \
    -DTrilinos_ENABLE_MueLu:BOOL=ON \
    -DTrilinos_ENABLE_EpetraExt:BOOL=OFF \
    -DTrilinos_ENABLE_AztecOO:BOOL=OFF \
    -DTrilinos_ENABLE_Belos:BOOL=ON \
    -DTrilinos_ENABLE_Ifpack2:BOOL=ON \
    -DTrilinos_ENABLE_Amesos2:BOOL=ON \
    -DTrilinos_ENABLE_Zoltan2:BOOL=ON \
    -DTrilinos_ENABLE_Ifpack:BOOL=OFF \
    -DTrilinos_ENABLE_Amesos:BOOL=OFF \
    -DTrilinos_ENABLE_Zoltan:BOOL=ON \
    -DTrilinos_ENABLE_STKMesh:BOOL=ON \
    -DTrilinos_ENABLE_STKSimd:BOOL=ON \
    -DTrilinos_ENABLE_STKIO:BOOL=ON \
    -DTrilinos_ENABLE_STKTransfer:BOOL=ON \
    -DTrilinos_ENABLE_STKSearch:BOOL=ON \
    -DTrilinos_ENABLE_STKUtil:BOOL=ON \
    -DTrilinos_ENABLE_STKTopology:BOOL=ON \
    -DTrilinos_ENABLE_STKUnit_tests:BOOL=ON \
    -DTrilinos_ENABLE_STKUnit_test_utils:BOOL=ON \
    -DTrilinos_ENABLE_Gtest:BOOL=ON \
    -DTrilinos_ENABLE_SEACASExodus:BOOL=ON \
    -DTrilinos_ENABLE_SEACASEpu:BOOL=ON \
    -DTrilinos_ENABLE_SEACASExodiff:BOOL=ON \
    -DTrilinos_ENABLE_SEACASNemspread:BOOL=ON \
    -DTrilinos_ENABLE_SEACASNemslice:BOOL=ON \
    -DTrilinos_ENABLE_SEACASIoss:BOOL=ON \
    -D TPL_ENABLE_Netcdf:BOOL=ON \
    -D   Netcdf_LIBRARY_DIRS:PATH="${SEMS_NETCDF_ROOT}/lib" \
    -D   Netcdf_INCLUDE_DIRS:PATH="${SEMS_NETCDF_ROOT}/include" \
    -D TPL_Netcdf_PARALLEL:BOOL=ON \
    -D TPL_ENABLE_Pnetcdf:BOOL=ON \
    -D   Pnetcdf_LIBRARY_DIRS:PATH="${SEMS_NETCDF_ROOT}/lib" \
    -D   Pnetcdf_INCLUDE_DIRS:PATH="${SEMS_NETCDF_ROOT}/include" \
    -D TPL_ENABLE_HDF5:BOOL=ON \
    -D   HDF5_DIR:PATH="${SEMS_HDF5_ROOT}" \
    -D BoostLib_INCLUDE_DIRS="${SEMS_BOOST_ROOT}/include" \
    -D BoostLib_LIBRARY_DIRS="${SEMS_BOOST_ROOT}/lib" \
    -DTrilinos_ASSERT_MISSING_PACKAGES=OFF \
    $EXTRA_ARGS \
    $trilinos_source_dir
```

which yield this output from io_info:
``$ ./install/trilinos/bin/io_info --config

Supported database types:
	catalyst dof dof_exodus exodus exodusII exodusii gen_struc generated genesis heartbeat 

Third-Party Library Configuration Information:

	Exodus Version 7.20
		Parallel enabled
		Thread Safe NOT enabled
		Deprecated Functions available

	NetCDF Version 4.4.1
		HDF5 enabled (1.8.12)
		parallel IO enabled via HDF5 and/or PnetCDF
		parallel IO enabled via PnetCDF (1.8.1 of 28 Jan 2017)
		NC_HAVE_META_H defined
		API Version 2 support enabled`
```
I am now able to run the test correctly using `ctest` however I am still seeing test failures...
I am looking closely at the `karmanVortex` test (it's the fastest to finish) and it looks like karmanVortex.norm is pretty close to karmanVortex.norm.gold but net exactly spot on. Is this the issue?
[karmanVortex.norm.log](https://github.com/Exawind/nalu-wind/files/3292355/karmanVortex.norm.log)
[karmanVortex.norm.gold.log](https://github.com/Exawind/nalu-wind/files/3292358/karmanVortex.norm.gold.log)

**Comment by alanw0** [comment]
@lucbv For your trilinos options, rather than individually enabling a bunch of STK sub-packages, it is better to just enable STK (-DTrilinos_ENABLE_STK:BOOL=ON) and then disable certain sub-packages if you need to (but I don't think you will need to). Anyway, the reason this is better is because there are a couple of new sub-packages which you aren't getting, such as STKNGP_TEST which many of stk's unit-tests depend on. Also, in the future nalu-wind will need STKBalance although that isn't needed yet. Final note, there is no need to enable/disable STKClassic, that doesn't exist any more.

I don't know why your tests are failing. What type of machine and compiler are you using? Is it one of the combinations that is on the nightly dashboard?

**Comment by lucbv** [comment]
@alanw0 thanks for the tips, in my latest configuration script I removed STKClassic as CMake rightly marked the option as unused. I will change to using `-DTrilinos_ENABLE_STK:BOOL=ON`.

Regarding the failing test I think this is something worth investigating. I am running these on my workstation since it is where I program most of the time. Unfortunately SEMS on the SON does not have modules that would allow me to match exactly any of the configurations on the dashboard but then again that should not matter. In my opinion developers should be able to work on their own machine... If that means that the tolerance for the regression test needs to be pushed up a bit from 1e-15 to 1e-12 then that's fine. As long as you keep the right tolerance for the nightly build you should be able to develop on different machines while keeping canonical checks...

Let us see what @sayerhs think of this? If I need to have exact matching for the regression tests then I will need an account on a machine where I can build and run with the same configuration as the dashboard.

**Comment by sayerhs** [comment]
@alanw0 It is near impossible to match the gold norms if we are not building with the exact same versions and optimization flags. Furthermore, @lucbv has disabled SuperLU and that will definitely introduce diffs and is different from any of the nightly build configurations. The reason I think his changes are OK is because the test is failing with the exact same diff both before and after his change. 

@lucbv Regarding your comment about relaxing the tolerance from `1e-15` to `1e-12`, that wouldn't help in this case because the tests are failing with diffs of `~O(1e-4)`.

```
1: ablNeutralEdge                      FAILED:   114.5805 s max-diff: 6.098180e-04
```

**Comment by lucbv** [comment]
@sayerhs I could generate my own set off `.norm.gold` files using nalu-wind/master and then recompile using my own branch nad run ctest.
This would tell me if I have a difference between `master` and my `local_branch` on my machine.

**Comment by sayerhs** [comment]
@alanw0 Can you confirm that you are able to get passing tests with GCC builds using the [snl-ceerws](https://github.com/sayerhs/exawind-builder/blob/master/README.md) configuration on your workstation? If so, can you please help @lucbv get this environment setup on his workstation? I suspect it would be good to have a way to replicate nightly builds on his machine so that the future pull-requests discussed in #249 can be tested as they would be more involved than this one.

**Comment by alanw0** [comment]
@lucbv I did a fresh pull and build, and my system is Linux with gcc 7.2. I'm seeing some failing tests now, which is perplexing. These will need to be figured out.  I'm seeing the following diffs:
ablNeutralEdge                      FAILED:    37.4529 s max-diff: 4.974160e-11
dgNonConformalFluids                FAILED:    25.0819 s max-diff: 4.620002e-15
dgNonConformalFluidsEdge            FAILED:    20.8882 s max-diff: 1.820003e-15
tensor_tg_mms                       FAILED:    59.7838 s max-diff: 1.575644e-06

I think @rcknaus may know what's going on with tensor_tg_mms. The others could be some discrepancy in build options. In general, if you have the same diffs before and after your changes, then your changes are probably fine. But I do think we need to figure out what's up with these diffs that are happening in a project with no changes...

If you want me to help you get set up with the exawind-builder system on your machine, let me know.

**Comment by sayerhs** [comment]
@alanw0 do you have OpenMP enabled in trilinos? We have seen some failing tests on nightly dashboard with that enabled and so we now have OpenMP disabled for nightly tests if I remember correctly. Can you explicitly set `OMP_NUM__THREADS=1` and try?

**Comment by alanw0** [comment]
@sayerhs is it sufficient to set OMP_NUM_THREADS=1 or do I need to confirm that my build has openmp disabled?

**Comment by sayerhs** [comment]
I think it is sufficient to do the first, but you can check by looking at the `cmake_output.log` in the Trilinos build directory.

**Comment by alanw0** [comment]
cmake_output.log shows that openmp is off. I'll try updating my copy of trilinos, it might be a couple weeks old.

**Comment by lucbv** [comment]
@sayerhs I am turning on SuperLU support using `superlu/5.2.1`, I could also use `superlu_dist/5.2.2` if that helps further. I have been looking on various systems and cannot find `gcc/7.4.0` support, we have `gcc/7.2.0`, `gcc/7.3.0` and `gcc/8.1.0`, `gcc/8.2.0` on our SkyLake development machine.
If absolutely necessary I could maintain a local installation with the proper compiler/TPL versions but that would take some time to setup. I could ask for access to `eagle` and check my work over there?

**Comment by sayerhs** [comment]
@lucbv I am fine merging this pull request. I'll let @alanw0 make the call on that :)

**Comment by lucbv** [comment]
@sayerhs @alanw0 after turning on `SuperLU` and setting `OMP_NUM_THREADS=1` I can get a small set of tests (13 in total) to pass both on `master` and `TpetraSegregatedLinearSolver`.
I don't think that I'll get more to pass though since my trilinos and nalu configurations are pretty much identical (except for libraries version of course) to those used for nightly tests.

By the way we are supposed to have an ExaWind linear solvers meeting on Wednesday but since Jonathan is on vacation we could use that time to discuss how we want to handle the issue related to verifying correctness of PR?

**Comment by overfelt** [comment]
FYI: When I pull the branch and run on the Sandia CEE Lan I get the same four diffs as Alan and I get on the master, which I always get.  The lucbv:TpetraSegregatedLinearSystem branch seems fine.

**Comment by alanw0** [comment]
@overfelt thanks for checking that. This makes it clear that this commit is good.
@lucbv this commit can be merged. What kind of machine are you using, that makes it so hard to get the tests to work? In general you can know that your code change is good if you get the same diffs with and without your change. But if you're only getting 13 tests to pass, it would be hard to even compare the before/after diffs... In any case this commit is good to go.

**Comment by rcknaus** [comment]
I don't know how useful this is, but he's a chart (from December) of all the level of diffs you expect for all the tests given an order-of-operations type change
image

**Comment by alanw0** [comment]
Thanks @rcknaus what about tensor_tg_mms, which appears to be showing a diff of 1.e-6 in my clean project?

**Comment by rcknaus** [comment]
That test is super sensitive and only really matches the gold on the NREL machines.  It's a verification test, but doing multiple resolutions would make it our most expensive test in the regression suite, so probably the test itself should change in some way.   Alternatively, we just need looser tolerancing on it.

**Comment by sayerhs** [comment]
@alanw0 #198 is supposed to track `tensor_tg_mms`

**Comment by lucbv** [comment]
@rcknaus @alanw0 @sayerhs since this PR has been approved by everyone, it is bound to be closed, I propose to continue this discussion in the following issue: #255

**Comment by lucbv** [comment]
@sayerhs it would be nice to get this merged today so I can check that things look good on the dashboard tomorrow.
Also I already have some additional work ready for another PR...

**Pull request merged**
