### PR TITLE
Remove usage of deprecated stk_io methods.

### PR DESCRIPTION
**Pull request by alanw0**
**Pull-request type:**
- [ ] Bug fix 
- [ ] Documentation update
- [ ] Feature enhancement

## Description of the pull-request

*Provide a description of your proposed changes. If there is a related issue, please specify.**

## Checklist

**NOTE** The checklist below is a suggestion and not mandatory. You don't have
to _check all boxes_ to submit a pull request. However, please add a brief
explanation in your pull request summary explaining the omission for the benefit
of reviewers and developers.

*All pull requests*
- [ ] Builds successfully (*must test on at least one system/compiler combination*)
  - Operating systems 
    - [ ] Linux
    - [ ] MacOS
  - Compilers 
    - [ ] GCC
    - [ ] LLVM/Clang
    - [ ] Intel compilers
    - [ ] NVIDIA CUDA
- [ ] Compiles without warnings
- [ ] Passes all unit tests
- [ ] Passes all regression tests
- [ ] Documentation builds without errors

*For new code updates*
- [ ] Documentation updates - additions to user, theory, and verification manuals
- [ ] New unit tests providing coverage for new code, bug fixes etc.
- [ ] New regression tests exercising the new code

### CODE REVIEW

**Comment by alanw0** [comment]
This depends on a stk update that went into Trilinos develop today. If we want to wait for it to get into Trilinos master before merging this, that might be good.

**Review by jrood-nrel — APPROVED** [review]

**Comment by alanw0** [comment]
Looks like the trilinos merge from the develop branch to the master branch has failed the last few days. I'll keep an eye on it and merge this once that happens.

**Comment by jrood-nrel** [comment]
If the necessary updates are in trilinos develop, I would be fine merging this.

**Comment by alanw0** [comment]
> If the necessary updates are in trilinos develop, I would be fine merging this.

ok, I'll let you make the judgment call. The updates are in the trilinos develop branch. I was hesitant to merge, not wanting to break nalu-wind builds that use trilinos master.

**Pull request merged**
