### PR TITLE
Always dump input file to the logfile

### PR DESCRIPTION
**Pull request by psakievich**
This makes it so the input file is echoed into the log file so we always know what parameters were used to run the case.

What do people think?  It will make the logfiles larger, but it will also decrease uncertainty on what was used for a given run.

### CODE REVIEW

**Review by lawrenceccheung — APPROVED** [review]
I think this is a great idea.  It'll help in debugging and removing uncertainty about what was actually used in the input file.

Lawrence

**Review by ashesh2512 — APPROVED** [review]

**Review by ashesh2512 — APPROVED** [review]
What does the log file look like? Is a line of #  obvious enough at first glance to separate the input file dump from the rest of the log file?

**Review by alanw0 — APPROVED** [review]

**Comment by rcknaus** [comment]
This is a good change. It's also possible to push the input file into the output exodus files. I've found that useful before for documentation, since the output files often live around longer than the log files.

**Comment by psakievich** [comment]
We should make sure this behavior gets ported to the driver too.

**Pull request merged**
