### PR TITLE
Converting TurbViscSSTAlg to NGP

### PR DESCRIPTION
**Pull request by marchdf**

### CODE REVIEW

**Comment by sayerhs** [comment]
@marchdf can you resolve the conflicts for this to be merged?

**Comment by jrood-nrel** [comment]
I just tried the github editor to resolve the conflicts here. Never really used it before 🙂

**Comment by jrood-nrel** [comment]
Should we merge this? Then I can fix conflicts that will arise in my PR.

**Comment by jrood-nrel** [comment]
I'm going for it.

**Comment by sayerhs** [comment]
@marchdf This had to be reverted because of segfaults on GPU. we will revisit this later.

**Pull request merged**
