### PR TITLE
Shared import

### PR DESCRIPTION
**Pull request by rcknaus**
**Pull-request type:**
- [ ] Bug fix 
- [ ] Documentation update
- [x] Feature enhancement

## Description of the pull-request

More for discussion here.

Performs import from owned to a shared-not-owned solution before copying the tpetra vector(s) to the stk field.

Generally, this combines the periodic and shared communication step since we add the periodic dofs that don't have a primary on the process to the shared-not-owned map along with the regular shared-not-owned dofs.  I'm not really sure this is a good idea, but should make it so we can reduce the number of syncs (and the size of the communication a little) we make.  

This approach has some draw-backs---we use some more storage and we write to the primary nodes twice if they have a replica on the process.  It doesn't really improve anything if there's no periodic dofs.  I'm not really sure it handles all of wind's use cases.   Just thought I'd put it up as an idea.

## Checklist

**NOTE** The checklist below is a suggestion and not mandatory. You don't have
to _check all boxes_ to submit a pull request. However, please add a brief
explanation in your pull request summary explaining the omission for the benefit
of reviewers and developers.

*All pull requests*
- [x] Builds successfully (*must test on at least one system/compiler combination*)
  - Operating systems 
    - [x] Linux
    - [x] MacOS
  - Compilers 
    - [ ] GCC
    - [x] LLVM/Clang
    - [ ] Intel compilers
    - [x] NVIDIA CUDA
- [x] Compiles without warnings
- [x] Passes all unit tests
- [x] Passes all regression tests (don't have hypre hooked up, so some were skipped in my local run)
- [ ] Documentation builds without errors

*For new code updates*
- [ ] Documentation updates - additions to user, theory, and verification manuals
- [ ] New unit tests providing coverage for new code, bug fixes etc.
- [ ] New regression tests exercising the new code

### CODE REVIEW

**Comment by psakievich** [comment]
Interesting idea. I'm surprised to see just how many parallel communications you avoid. Seems like it could pay off depending on the communication cost. I haven't been following the gpu to gpu communication progress, but if we still have to copy to host to do our communication the it seems like it'd be a big win. Have you run any tests to compare the two yet?

**Comment by sayerhs** [comment]
@rcknaus This looks like a good idea that could benefit ABL precursor simulations. As @psakievich suggests, it would be great if we can document gains for the standard 5x5x1 km domain at 10m resolution. 

@psakievich For STK field parallel operations, the STK team has found it almost always faster to do the `device - host - mpi - host - device` than doing CUDA-aware transfers. I don't think that has changed still.

**Comment by rcknaus** [comment]
I can set up a 10m ABL but I probably won't get to it for a little while.  I did try it on a 384^3 taylor green vortex when I was working on this and saw about a 20-25% speed up on 4x5 GPUs.

**Comment by rcknaus** [comment]
I ran the 10m 5x5x1 ABL with 5 nodes with 4 volta gpus each.  Before applying this change, the average time-per-timestep (neglecting the first and last steps) was 6.78 seconds.  After applying, it was 5.42 seconds for a speedup of 25%.  The change causes a diff since things are ordered differently, but it's 4.69e-11 after 100 timesteps.

**Comment by sayerhs** [comment]
@rcknaus Do you want open this up from Draft to review?

**Comment by rcknaus** [comment]
This probably needs some more thought / testing to flesh out for use in the main code base.   I think I'll leave this on the backburner for a bit, but I might return to it later.

**Pull request closed without merging**
