### PR TITLE
Fixes errors in ghosting update for some overset mesh problems.

### PR DESCRIPTION
**Pull request by ddement**
Instead of trying to modify the ghosting for overset problems with relative motion, we now just rebuild the ghosting from scratch every time update_ghosting is called. This appears to fix errors such as those reported in #936

### CODE REVIEW

**Comment by ashesh2512** [comment]
@ddement So we are essentially recreating the ghosting object every time step. Is that accurate?

**Review by ashesh2512 — APPROVED** [review]

**Comment by ddement** [comment]
@ashesh2512 Exactly.  I'm sure there's a more efficient way to incrementally update it like we were attempting to do previously, but this approach should always produce a correct ghosting.  If this turns out to be a significant cost, we can readdress optimizing it at a later point.

**Comment by alanw0** [comment]
That's right. At each time step there is a list of elements that need to be ghosted. The list for the next time step includes a lot of the same elements, but some new elements get added, and some get dropped. We were trying to just incrementally update the list, rather than completely dropping the old list and adding the new list. (I worked on this years ago with Stefan.) Apparently the incremental update wasn't correct, so dropping all of the old ones and then ghosting the new list is easier to get correct. Hopefully the performance difference shouldn't be too great. Like David says, we can revisit this if there is a big performance difference.

**Review by alanw0 — APPROVED** [review]

**Review by ashesh2512 — APPROVED** [review]

**Comment by ashesh2512** [comment]
@gantech Could you please try the changes in this PR, for your simulations?

**Comment by alanw0** [comment]
We think this PR is ready to merge. I'm only hesitating because I don't want to breathe on anything until the challenge problem is finished.

**Comment by ashesh2512** [comment]
> We think this PR is ready to merge. I'm only hesitating because I don't want to breathe on anything until the challenge problem is finished.

I think that is a good life choice considering recent events

**Review by psakievich — APPROVED** [review]
I've stalled merging everything until we get it done as well. There are several pending PR's that are ready to merge.

**Pull request merged**
