### PR TITLE
WallDistEdgeSolver GPU conversion

### PR DESCRIPTION
**Pull request by jrood-nrel**
I'm not really sure if I'm close to done with this, but everything compiles and runs, except it's not clear to me why I get this error:
```
77: unknown file: Failure
77: C++ exception with description "Requirement( (field != nullptr) ) FAILED
77: Error occured at: my-nalu-wind/include/utils/StkHelpers.h:101
77: Error: Requested field does not exist: edge_area_vector
77: " thrown in the test body.
77: [  FAILED  ] WallDistKernelHex8Mesh.NGP_wall_dist_edge (2 ms)
```

### CODE REVIEW

**Comment by sayerhs** [comment]
@jrood-nrel This was my mistake. I put the `edgeAreaVec` field under [LowMachKernelHex8Mesh](https://github.com/Exawind/nalu-wind/blob/master/unit_tests/kernels/UnitTestKernelUtils.h#L329) instead of in `TestKernelHex8Mesh`. `edgeAreaVec` will be needed for all equation systems, and it might be better if the logic associated with `edgeAreaVec` was moved into the base class so that we don't have to re-declare this in each equation system test class. This would mean that we will need [fill_mesh_and_init_fields](https://github.com/Exawind/nalu-wind/blob/master/unit_tests/kernels/UnitTestKernelUtils.h#L361) even in the base class, which the subclasses call before initializing their own fields. Do you want to take a stab at the redesign?

**Comment by jrood-nrel** [comment]
I see. Thanks. I think I will try implementing `edgeAreaVector` in `WallDistKernelHex8Mesh` first and see if I can understand the commonalities between them enough to attempt the redesign.

**Comment by jrood-nrel** [comment]
Ok this works on the CPU now. I need to test it on the GPU, and then I will see if I can push `edgeAreaVec` up level of classes.

**Comment by jrood-nrel** [comment]
@sayerhs Does this look right?

**Pull request merged**
