### PR TITLE
Document how to run a simple example using regression test case data

### PR DESCRIPTION
**Pull request by neumantm**
This is useful to quickly check if the installation of nalu-wind works.

This was inspired by [a comment by @psakievich](https://github.com/Exawind/nalu-wind/issues/1070#issuecomment-1304081221)

### CODE REVIEW

**Comment by jrood-nrel** [comment]
Maybe we don't have enough documentation on it, but using `ctest` is the preferred method to run the regression tests.

**Comment by neumantm** [comment]
Yes I understood this.
The goal of this is to document how to (mis)use a regression test case as a very simple example to see if the installation works.
That is what @psakievich suggested in the comment I linked.
Maybe I should change the title of the PR.

**Comment by psakievich** [comment]
@neumantm would you also add in an example of running the unittests?  I think my preference for people testing the code is first to run the unit tests and then they can manually run the regression tests.  We always build the unit tests right now, and as a plus they don't require the mesh repo which is 600MB (recently down from 1GB thanks to @jrood-nrel :pray:)

**Comment by neumantm** [comment]
Sure. Makes sense. 
They just need to run `unittestX`, am I right?

**Review by psakievich — APPROVED** [review]

**Comment by psakievich** [comment]
@neumantm yes that is correct.

**Comment by marchdf** [comment]
@psakievich this also should have been merged?

**Pull request merged**
