### PR TITLE
Allow UnitTestScalarOpenAlgorithm to run with unitTest2

### PR DESCRIPTION
**Pull request by jrood-nrel**

### CODE REVIEW

**Comment by sayerhs** [comment]
Pull request #300  is going to remove `AssembleScalarEdgeOpenSolverAlgorithm`, so this unit test will go away at that time also. I don't think there is need to do this change.

**Comment by jrood-nrel** [comment]
This can stop that test from failing until then though.

**Comment by sayerhs** [comment]
This test is not checking anything, it was created to provide gold values for another test. My vote will be to remove the test (as the base source code is also going to go away). In other tests we do this: https://github.com/Exawind/nalu-wind/blob/master/unit_tests/edge_kernels/UnitTestScalarAdvDiffEdge.C#L42

**Comment by jrood-nrel** [comment]
Fair enough.

**Pull request closed without merging**
