### PR TITLE
Fix build errors from latest trilinos updates

### PR DESCRIPTION
**Pull request by sayerhs**
See #674 for details

### CODE REVIEW

**Comment by sayerhs** [comment]
@alanw0 found it easier to just cherry-pick your commit instead of fiddling with the modified submodule state.

**Comment by alanw0** [comment]
I got a build error with my PR this morning also. Is it a chicken-and-egg issue where this change is necessary to work with the latest trilinos but trilinos hasn't been updated because it wouldn't build without this change?

**Comment by sayerhs** [comment]
@alanw0 Yes, I need to update the trilinos docker image that is used for CI tests. I'll trigger this docker update so that subsequent CI updates work properly

**Comment by alanw0** [comment]
ok. once this is in, I'll be interested to see how the nalu-wind tests run. In particular on a mac/clang platform. Stefan is seeing errors beneath stk-io, but only on mac clang, not on his gcc and intel builds.

**Pull request merged**
