### PR TITLE
NGP Field manager integration and deprecating ElemDataRequestsNGP

### PR DESCRIPTION
**Pull request by sayerhs**
This pull request introduces `ngp::FieldManager` in nalu-wind to manage field accesses within the NGP interface. It removes the usage of ElemDataRequestsNGP for most unit tests and replaces them with ElemDataRequestsGPU.

### CODE REVIEW

**Comment by sayerhs** [comment]
@alanw0 The next steps are:

- Update `SharedMemData` to use `ngp::ConnectedNodes` 
- Convert `AssembleElemSolverAlgorithm` and `AssembleFaceElemSolverAlgorithm` to use ElemDataRequestsGPU and replace usages of `stk::mesh` data structures with `ngp::` data structures
- Convert `TeamHandleType` and `HostShmem` to  `DeviceTeamHandleType` and `DeviceShmem` 
- Update Kernels to take the appropriate data types in `execute` function

**Comment by alanw0** [comment]
@sayerhs those steps sound good. Do you want me to do some of them, or are you cruising through them?

**Comment by sayerhs** [comment]
@alanw0 Is then your recommendation that we shouldn't use `ngp::FieldManager` in `nalu-wind` yet and should adopt a _wait and see_ strategy? If so, I'll go ahead and close the pull request.

**Comment by alanw0** [comment]
@sayerhs No, I think we should go ahead with this. We can easily switch later if stk ends up wrapping the ngp stuff in under stk-mesh.

**Comment by sayerhs** [comment]
@alanw0 @overfelt 

This pull request works with ScratchViews now:

```
sananth@ascicgpu15 (f/ngp-field-mgr)$ ./unittestX --gtest_filter=*.*gpMesh:*.*GPU:*.ScratchViews
Note: Google Test filter = *.*gpMesh:*.*GPU:*.ScratchViews
[==========] Running 3 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from Hex8MeshWithNSOFields
[ RUN      ] Hex8MeshWithNSOFields.ElemDataRequestsGPU
[       OK ] Hex8MeshWithNSOFields.ElemDataRequestsGPU (4 ms)
[ RUN      ] Hex8MeshWithNSOFields.ScratchViews
TestKernel::execute!!
TestKernel::execute!!
TestKernel::execute!!
TestKernel::execute!!
TestKernel::execute!!
TestKernel::execute!!
TestKernel::execute!!
TestKernel::execute!!
[       OK ] Hex8MeshWithNSOFields.ScratchViews (12 ms)
[----------] 2 tests from Hex8MeshWithNSOFields (16 ms total)

[----------] 1 test from NgpMesh
[ RUN      ] NgpMesh.realmNgpMesh
[       OK ] NgpMesh.realmNgpMesh (9 ms)
[----------] 1 test from NgpMesh (9 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 2 test cases ran. (25 ms total)
[  PASSED  ] 3 tests.
```

**Pull request merged**
