### PR TITLE
Fix error in unit test from unsynched bulk

### PR DESCRIPTION
**Pull request by marchdf**
Fixes these errors:
```
error: 'show' is not a valid command.
C++ exception with description "Requirement( bulkData.in_synchronized_state() ) FAILED                                                                                                                                                                                [63/29722]
Error occurred at: stk_mesh/stk_mesh/base/SkinBoundary.cpp:88

Error: Cannot use create_all_sides while in another mod cycle.
" thrown in the test body.
```

### CODE REVIEW

**Comment by marchdf** [comment]
These edits fix the errors but I now get another error later in the unit tests:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x0000000184688704 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x00000001846bfc28 libsystem_pthread.dylib`pthread_kill + 288
    frame #2: 0x00000001845cdae8 libsystem_c.dylib`abort + 180
    frame #3: 0x00000001844eee28 libsystem_malloc.dylib`malloc_vreport + 908
    frame #4: 0x00000001845055d4 libsystem_malloc.dylib`malloc_zone_error + 104
    frame #5: 0x000000018450528c libsystem_malloc.dylib`free_list_checksum_botch + 40
    frame #6: 0x00000001844e6f5c libsystem_malloc.dylib`tiny_free_list_remove_ptr + 452
    frame #7: 0x00000001844e66c8 libsystem_malloc.dylib`tiny_free_no_lock + 1060
    frame #8: 0x00000001844e6120 libsystem_malloc.dylib`free_tiny + 496
    frame #9: 0x000000010097a310 unittestX`Kokkos::HostSpace::impl_deallocate(char const*, void*, unsigned long, unsigned long, Kokkos_Profiling_SpaceHandle) const + 332
    frame #10: 0x000000010097a3f4 unittestX`Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, void>::~SharedAllocationRecord() + 120
    frame #11: 0x000000010001ae6c unittestX`Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, unsigned int, true>>::~SharedAllocationRecord() + 216
    frame #12: 0x000000010001ad8c unittestX`Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, unsigned int, true>>::~SharedAllocationRecord() + 12
    frame #13: 0x0000000108cf5a48 libnalu.dylib`Kokkos::Impl::SharedAllocationRecord<void, void>::decrement(Kokkos::Impl::SharedAllocationRecord<void, void>*) + 60
    frame #14: 0x000000010027ab08 unittestX`Tpetra::Details::WrappedDualView<Kokkos::DualView<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void>>::~WrappedDualView() + 88
    frame #15: 0x000000010027a78c unittestX`Tpetra::MultiVector<double, int, long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::~MultiVector() + 132
    frame #16: 0x000000010027ac94 unittestX`sierra::nalu::matrix_free::DiagonalFixture::~DiagonalFixture() + 48
    frame #17: 0x000000010026a054 unittestX`sierra::nalu::matrix_free::DiagonalFixture_diagonal_executes_Test::~DiagonalFixture_diagonal_executes_Test() + 12
    frame #18: 0x00000001009880d4 unittestX`void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 80
    frame #19: 0x000000010098994c unittestX`testing::TestInfo::Run() + 336
    frame #20: 0x000000010098a37c unittestX`testing::TestSuite::Run() + 288
    frame #21: 0x000000010099793c unittestX`testing::internal::UnitTestImpl::RunAllTests() + 984
    frame #22: 0x0000000100997370 unittestX`bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) + 80
    frame #23: 0x00000001009972ec unittestX`testing::UnitTest::Run() + 124
    frame #24: 0x0000000100009968 unittestX`main + 748
    frame #25: 0x0000000184367f28 dyld`start + 2236
```

@alanw0  @psakievich thought you might be able to help on this one?

**Comment by marchdf** [comment]
I updated the comment above with a stack trace from a debug build

**Review by alanw0 — APPROVED** [review]
Yes those changes look good to me.
i.e., create_all_sides needs to be called outside of the modification_begin/modification_end pair of calls.
stk used to allow it to be called 'inside' those calls, but behavior was sometimes incorrect.

**Comment by rcknaus** [comment]
> @alanw0 and @rcknaus : @psakievich thought you might be able to help on this one?

Looks like it was trying to write to past the end of multivector. do we have asan testing still?

**Review by psakievich — APPROVED** [review]

**Comment by marchdf** [comment]
```
[----------] Global test environment tear-down
[==========] 572 tests from 136 test suites ran. (202985 ms total)
[  PASSED  ] 571 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] VOFKernelHex8Mesh.NGP_adv_diff_edge_tpetra
```
I think we can merge. The failing test has a 1e-14 diff. Thanks @rcknaus for fixing that last issue!

**Pull request merged**
