### PR TITLE
Remove more CUDA ifdefs from node kernels

### PR DESCRIPTION
**Pull request by jrood-nrel**
#316 allows me to finish 7 more node kernels. Looks like the remaining ones have more suminto issues I will see if I can handle.

### CODE REVIEW

**Comment by sayerhs** [comment]
@jrood-nrel can you provide an example node kernel that is having issues?

**Comment by jrood-nrel** [comment]
Here is an example of a node kernel that still fails:
```
1: /home/jrood/exawind/my-nalu-wind/unit_tests/node_kernels/UnitTestEnthalpyABLForceNode.C:37: Failure
1:       Expected: helperObjs.linsys->numSumIntoCalls_
1:       Which is: 0
1: To be equal to: 8
1: [  FAILED  ] EnthalpyKernelHex8Mesh.NGP_abl_force (8 ms)
```

**Comment by sayerhs** [comment]
Ah yes, it seems that @alanw0 decided to remove the counter and in his example removed that line from the unit test that he had converted: https://github.com/Exawind/nalu-wind/pull/305/files#diff-8e04f73617cb40e46948a977a476db26L67

**Comment by jrood-nrel** [comment]
Ok, are we fine if I just remove these lines then?

**Comment by sayerhs** [comment]
It would be good to get @alanw0's feedback on why he decided to take it out, before we remove `EXPECT_*` statements from unit tests.

**Comment by alanw0** [comment]
Hmm, I had forgotten about that. I'm not sure. I may have removed it from a test I was fixing, and then forgot to go back to it and get that part working. I think it would require putting that member in a view and copying it back up to the host to check it at the end, but maybe there's a simpler way to do it.

**Pull request merged**
